version: "3.7"
services:
  app:
    container_name: ibuddy
    build:
      dockerfile: Dockerfile
      context: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:5.0
    restart: on-failure
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
    name: mongo_data